//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 06:58:17 PM GMT+05:30 
//


package com.photon.phresco.bby;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.photon.phresco.bby package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.photon.phresco.bby
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Promos.Promo }
     * 
     */
    public Promos.Promo createPromosPromo() {
        return new Promos.Promo();
    }

    /**
     * Create an instance of {@link Promos }
     * 
     */
    public Promos createPromos() {
        return new Promos();
    }

}
