--Drop Tables
drop table PROMO_SKUS cascade constraints;
drop table CATEGORIES cascade constraints;
drop table CATEGORY_TREE cascade constraints;
drop table ATTRIBUTES cascade constraints;
drop table ATTRIBUTE_VALUES cascade constraints;
drop table CONTEXTS cascade constraints;
drop table CONTEXT_KEYWORDS cascade constraints;
drop table BANNERS cascade constraints;
drop table BANNER_CONTEXTS cascade constraints;
drop table BANNER_TEMPLATE_META cascade constraints;
drop table BANNER_TEMPLATES cascade constraints;
drop table CONTEXT_FACETS cascade constraints;
drop table FACETS cascade constraints;
drop table CATEGORY_FACET cascade constraints;
drop table FACET_ATTR_VALUE_ORDER cascade constraints;
drop table BATCH_JOB_EXECUTION cascade constraints;
drop table PROMOS cascade constraints;
drop table ROLES cascade constraints;
drop table KEYWORD_REDIRECTS cascade constraints;
drop table SYNONYMS cascade constraints;
drop table BOOSTS_AND_BLOCKS cascade constraints;
drop table BOOSTS_AND_BLOCKS_PRODUCTS cascade constraints;
drop table STATUS cascade constraints;
drop table USERS cascade constraints;
drop table SYNONYM_TYPES cascade constraints;
drop table SEARCH_PROFILES cascade constraints;
drop table SYNONYM_TERMS cascade constraints;
drop table AF_BATCH_JOB_EXECUTION cascade constraints;
drop table FACETS_DISPLAY_ORDER cascade constraints;
drop table SKU_HISTORY cascade constraints;

DROP SEQUENCE PROMO_SEQ;
DROP SEQUENCE REDIRECTS_SEQ;
DROP SEQUENCE FACET_SEQ;
DROP SEQUENCE CATG_FACET_SEQ;
DROP SEQUENCE BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE SYNONYMS_SEQ;
DROP SEQUENCE BOOSTS_AND_BLOCKS_PRODUCTS_SEQ;
DROP SEQUENCE BOOSTS_AND_BLOCKS_SEQ;
DROP SEQUENCE HIBERNATE_SEQUENCE;
DROP SEQUENCE AF_BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE FACETS_DISPLAY_ORDER_SEQ;
DROP SEQUENCE SKU_HISTORY_SEQ;

--Create sequences 
CREATE SEQUENCE PROMO_SEQ;
CREATE SEQUENCE REDIRECTS_SEQ;
CREATE SEQUENCE FACET_SEQ;
CREATE SEQUENCE CATG_FACET_SEQ;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE SYNONYMS_SEQ;
CREATE SEQUENCE BOOSTS_AND_BLOCKS_PRODUCTS_SEQ;
CREATE SEQUENCE BOOSTS_AND_BLOCKS_SEQ;
CREATE SEQUENCE HIBERNATE_SEQUENCE;
CREATE SEQUENCE AF_BATCH_JOB_EXECUTION_SEQ;
CREATE SEQUENCE FACETS_DISPLAY_ORDER_SEQ;
CREATE SEQUENCE SKU_HISTORY_SEQ;

  CREATE TABLE "STATUS"
  (
     "STATUS_ID"   NUMBER(19, 0) NOT NULL,
     "STATUS_NAME" NVARCHAR2(15),
     CONSTRAINT "PK_STATUS" PRIMARY KEY ("STATUS_ID"),
     CONSTRAINT "CK_STATUS_NAME" UNIQUE ("STATUS_NAME")
  ); 
  
  
  CREATE TABLE "ROLES" 
   (	
    "ID" NUMBER(19,0) NOT NULL , 
	"NAME" NVARCHAR2(20) NOT NULL, 
	"DESCRIPTION" NVARCHAR2(40), 
	 CONSTRAINT "PK_ROLES" PRIMARY KEY ("ID")
   ) ;
  
 CREATE TABLE "USERS"
  (
     "USER_ID"    NUMBER(19, 0) NOT NULL,
     "ACTIVE"     NUMBER(1, 0),
     "EMAIL"      NVARCHAR2(255),
     "FIRST_NAME" NVARCHAR2(255),
     "LAST_NAME"  NVARCHAR2(255),
     "LOGIN_NAME" NVARCHAR2(255),
     "PASSWORD"   NVARCHAR2(255),
     "ROLE_ID" 	  NUMBER DEFAULT 2, 
     "UPDATED_BY" NVARCHAR2(255), 
     "UPDATED_DATE" DATE, 
     CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID"),
     CONSTRAINT "UC_USERS_EMAIL" UNIQUE ("EMAIL"),
     CONSTRAINT "FK_USERS_ROLES_ID" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES" ("ID")
  );  
  
  CREATE TABLE "SYNONYM_TYPES"
  (
    "ID"         NUMBER NOT NULL ENABLE,
    "NAME"       NVARCHAR2(255),
    "CREATED_BY" NUMBER,
    "CREATED_DATE" DATE,
    "UPDATED_BY" NUMBER,
    "UPDATED_DATE" DATE,
    CONSTRAINT "PK_SYNONYM_TYPES" PRIMARY KEY ("ID")
  );
  
  CREATE TABLE  "SEARCH_PROFILES"
  (
     "SEARCH_PROFILE_ID" NUMBER(19, 0) NOT NULL,
     "COLLECTIONS"       NVARCHAR2(255) NOT NULL,
     "DEFAULT_PATH"      NVARCHAR2(255) NOT NULL,
     "LASTMODIFIER_ID"   NVARCHAR2(20) NOT NULL,
     "MODIFIED_DATE"     DATE NOT NULL,
     "PIPELINE_NAME"     NVARCHAR2(255) NOT NULL,
     "PROFILE_NAME"      NVARCHAR2(255) NOT NULL,
     "RANK_PROFILE_NAME" NVARCHAR2(255) NOT NULL,
     "SEARCH_FIELD_NAME" NVARCHAR2(255) NOT NULL,
     "TOP_CATEGORY_ID"   NVARCHAR2(255) NOT NULL,
     "SYNONYM_LIST_ID"   NUMBER(19, 0),
     CONSTRAINT "PK_SEARCH_PROFILES" PRIMARY KEY ("SEARCH_PROFILE_ID"),
     CONSTRAINT "FK_SEARCH_PROFILES_LIST_ID" FOREIGN KEY ("SYNONYM_LIST_ID")
     REFERENCES  "SYNONYM_TYPES" ("ID")
  );  
  
  CREATE TABLE  "CATEGORIES"
  (
     "CATEGORY_NODE_ID" NVARCHAR2(25) NOT NULL ENABLE,
     "CATEGORY_PATH"    NVARCHAR2(255) NOT NULL ENABLE,
     "MODIFIED_DATE"    DATE,
     "IS_ACTIVE"  NVARCHAR2(2) NOT NULL ENABLE,
     "ALSO_FOUND" NVARCHAR2(2000),
     CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("CATEGORY_NODE_ID")
  );  
  
 CREATE TABLE  "CATEGORY_TREE"
  (
     "CATEGORY_ID"   NUMBER(19, 0) NOT NULL,
     "CATEGORY_TREE" CLOB,
     "MODIFIED_DATE" DATE,
     "VERSION"       NUMBER(19, 0) NOT NULL,
     CONSTRAINT "PK_CATEGORY_TREE" PRIMARY KEY ("CATEGORY_ID")
  );
  
 CREATE TABLE  "ATTRIBUTES"
  (
     "ATTRIBUTE_ID"   NUMBER(19, 0) NOT NULL,
     "ATTRIBUTE_NAME" NVARCHAR2(255),
     "IS_ACTIVE"  NVARCHAR2(2) NOT NULL,
     CONSTRAINT "PK_ATTRIBUTES" PRIMARY KEY ("ATTRIBUTE_ID")
  );  

 CREATE TABLE  "ATTRIBUTE_VALUES"
  (
     "ATTRIBUTE_VALUE_ID" NUMBER(19, 0) NOT NULL,
     "ATTRIBUTE_VALUE"    NVARCHAR2(255),
     "IS_ACTIVE"  NVARCHAR2(2) NOT NULL,
     "ATTRIBUTE_ID"       NUMBER(19, 0),
     CONSTRAINT "PK_ATTRIBUTE_VALUES" PRIMARY KEY ("ATTRIBUTE_VALUE_ID"),
     CONSTRAINT "FK_ATTR_VALUES_ATTR_ID" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES
      "ATTRIBUTES" ("ATTRIBUTE_ID")
  ); 
  
  
  CREATE TABLE "SYNONYMS"
  (
    "ID"             NUMBER(19,0) NOT NULL,
    "DIRECTIONALITY" NVARCHAR2(20),
    "MATCH_TYPE"     NVARCHAR2(20),
    "PRIMARY_TERM"   NVARCHAR2(255),
    "TYPE_ID"        NUMBER,
    "CREATED_BY"     NUMBER,
    "CREATED_DATE" DATE,
    "UPDATED_BY" NUMBER,
    "UPDATED_DATE" DATE,
    "START_DATE" DATE,
    "END_DATE" DATE,
    "STATUS_ID" NUMBER,
    "NAME"      NVARCHAR2(255),
    CONSTRAINT "PK_SYNONYMS" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_SYNONYMS_STATUS" FOREIGN KEY ("STATUS_ID") REFERENCES "STATUS" ("STATUS_ID") ENABLE,
    CONSTRAINT "FK_SYNONYMS_CREATED_BY" FOREIGN KEY ("CREATED_BY") REFERENCES "USERS" ("USER_ID") ENABLE,
    CONSTRAINT "FK_SYNONYMS_TYPE" FOREIGN KEY ("TYPE_ID") REFERENCES "SYNONYM_TYPES" ("ID") ENABLE,
    CONSTRAINT "FK_SYNONYM_UPDATED_BY" FOREIGN KEY ("UPDATED_BY") REFERENCES "USERS" ("USER_ID") ENABLE,
    CONSTRAINT "CK_SYNONYM_MATCH_TYPE" CHECK(MATCH_TYPE IN ('Exact', 'Broad')),
    CONSTRAINT "CK_SYNONYM_DIRECTIONALITY" CHECK(DIRECTIONALITY IN ('One-way', 'Two-way'))
  );
  
  CREATE TABLE "SYNONYM_TERMS"
  (
    "SYNONYM_ID" NUMBER(19,0) NOT NULL ENABLE,
    "TERM"       NVARCHAR2(200) NOT NULL ENABLE,
    CONSTRAINT "PK_SYNONYM_TERMS" PRIMARY KEY ("SYNONYM_ID", "TERM"), 
    CONSTRAINT "FK_SYNONYM_TERMS" FOREIGN KEY ("SYNONYM_ID") REFERENCES "SYNONYMS" ("ID") ENABLE
  );

  CREATE TABLE  "CONTEXTS"
  (
     "CONTEXT_ID"        NUMBER(19, 0) NOT NULL ENABLE,
     "CATEGORY_NODE_ID" NVARCHAR2(50),
     "INHERITABLE"       NUMBER(19, 0),
     "SEARCH_PROFILE_ID" NUMBER(19, 0),
     "IS_ACTIVE"  NVARCHAR2(2) NOT NULL,
     CONSTRAINT "PK_CONTEXTS" PRIMARY KEY ("CONTEXT_ID"),
     CONSTRAINT "FK_CONTEXTS_SEARCH_PROF_ID" FOREIGN KEY ("SEARCH_PROFILE_ID")
     REFERENCES  "SEARCH_PROFILES" ("SEARCH_PROFILE_ID"),
     CONSTRAINT "FK_CONTEXTS_CATEGORY_NODE_ID" FOREIGN KEY ("CATEGORY_NODE_ID")
     REFERENCES  "CATEGORIES" ("CATEGORY_NODE_ID")
  );  
  
  
  CREATE TABLE  "CONTEXT_KEYWORDS"
  (
     "KEYWORD"         NVARCHAR2(255) NOT NULL ENABLE,
     "CONTEXT_KEYWORD" NUMBER(19, 0),
     CONSTRAINT "PK_CONTEXT_KEYWORDS" PRIMARY KEY ("CONTEXT_KEYWORD", "KEYWORD"),
     CONSTRAINT "FK_CTX_KEY_KEYOWRDID" FOREIGN KEY ("CONTEXT_KEYWORD")
     REFERENCES  "CONTEXTS" ("CONTEXT_ID") ENABLE
  ); 
  
  CREATE TABLE "BANNERS" 
   (	
    "BANNER_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BANNER_NAME" NVARCHAR2(255) NOT NULL ENABLE, 
	"BANNER_PRIORITY" NUMBER(19,0), 
	"BANNER_TEMPLATE" NVARCHAR2(255), 
	"BANNER_TYPE" NUMBER(19,0), 
	"STATUS_ID" NUMBER(2,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"UPDATED_DATE" DATE, 
	"CREATED_DATE" DATE, 
	"CREATED_BY" NUMBER(19,0), 
	"UPDATED_BY" NUMBER(19,0), 
	 CONSTRAINT "PK_BANNERS" PRIMARY KEY ("BANNER_ID"), 
	 CONSTRAINT "FK_BANNERS_STATUS_ID" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "STATUS" ("STATUS_ID"), 
	 CONSTRAINT "FK_BANNERS_UPDATED_BY" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "USERS" ("USER_ID"), 
	 CONSTRAINT "FK_BANNERS_CREATED_BY" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "USERS" ("USER_ID")
   );
   
  CREATE TABLE  "BANNER_CONTEXTS"
  (
     "CONTEXT_ID" NUMBER(19, 0) NOT NULL ENABLE,
     "BANNER_ID"  NUMBER(19, 0) NOT NULL ENABLE,
     CONSTRAINT "PK_BANNER_CONTEXTS" PRIMARY KEY("CONTEXT_ID", "BANNER_ID"),
     CONSTRAINT "FK_BANNER_CONTEXTS_CTX_ID" FOREIGN KEY ("CONTEXT_ID")
     REFERENCES  "CONTEXTS" ("CONTEXT_ID") ENABLE,
     CONSTRAINT "FK_BANNER_CONTEXTS_BNR_ID" FOREIGN KEY ("BANNER_ID") REFERENCES
      "BANNERS" ("BANNER_ID") ENABLE
  );  
  
  CREATE TABLE  "BANNER_TEMPLATE_META"
  (
     "BANNER_TEMPLATE_ID"           NUMBER(19, 0) NOT NULL ENABLE,
     "BANNER_TEMPLATE_FIELD_LIST"   NVARCHAR2(255) NOT NULL ENABLE,
     "BANNER_TEMPLATE_HEADER_COUNT" NUMBER(19, 0) NOT NULL ENABLE,
     "BANNER_TEMPLATE_NAME"         NVARCHAR2(255) NOT NULL ENABLE,
     "BANNER_TEMPLATE_SLOT_COUNT"   NUMBER(19, 0) NOT NULL ENABLE,
     CONSTRAINT "PK_BANNER_TEMPLATES" PRIMARY KEY ("BANNER_TEMPLATE_ID"),
     CONSTRAINT "UK_BANNER_TEMPLATE_NAME" UNIQUE ("BANNER_TEMPLATE_NAME")
  );  
 
  
 CREATE TABLE  "BANNER_TEMPLATES"
  (
     "TEMPLATE_ID" NUMBER(19, 0) NOT NULL ENABLE,
     "TEMPLATE_TYPE"    NVARCHAR2(15),
     "TEMPLATE_HEADER"      NVARCHAR2(255),
     "SKU_POSITION"  NUMBER(2, 0),
     "SKUS"  NVARCHAR2(255),
     "BANNER_ID"     NUMBER(19, 0),
     CONSTRAINT "PK_BNR_TEMPS" PRIMARY KEY ("TEMPLATE_ID"),
     CONSTRAINT "FK_BNR_TEMPS_ID" FOREIGN KEY ("BANNER_ID") REFERENCES
      "BANNERS" ("BANNER_ID") ENABLE
  );    
  
  
  	CREATE TABLE  "FACETS"
  (
     "FACET_ID"          NUMBER(19, 0) NOT NULL,
     "DISPLAY_NAME"      NVARCHAR2(100) NOT NULL,
     "SYSTEM_NAME"       NVARCHAR2(100) NOT NULL,
     "DISPLAY_MODE"      NVARCHAR2(15) NOT NULL,
     "DISPLAY"           NVARCHAR2(1) NOT NULL,
     "DISPLAY_RECURRENCE" NVARCHAR2(1) NOT NULL,
     "DISPLAY_FACET_REMOVE_LNK" NVARCHAR2(1) NOT NULL,
     "DISPLAY_MOB_FACET" NVARCHAR2(1) NOT NULL,
     "DISPLAY_MOB_FACET_REMOVE_LNK" NVARCHAR2(1) NOT NULL,
     "GLOSSARY_ITEM"     NUMBER(10, 0),
     "SORT_TYPE"         NVARCHAR2(18) NOT NULL,
     "MIN_ATTR_VALUE"    NUMBER(2, 0) NOT NULL,
     "MAX_ATTR_VALUE"    NUMBER(3, 0),
     "POSITION"          NVARCHAR2(10),
     "START_DATE"        DATE NOT NULL,
     "END_DATE"          DATE,
     "CREATED_DATE"      DATE NOT NULL,
     "CREATED_BY"        NUMBER(10, 0),
     "UPDATED_DATE"     DATE NOT NULL,
     "UPDATED_BY"       NUMBER(10, 0),
     "ATTRIBUTE_ID"      NUMBER(19, 0),
     "STATUS_ID"         NUMBER(19, 0),
     CONSTRAINT "PK_FACET_FACET_ID" PRIMARY KEY ("FACET_ID"),
     CONSTRAINT "FK_FACET_CREATED_BY" FOREIGN KEY ("CREATED_BY") REFERENCES
      "USERS" ("USER_ID"),
     CONSTRAINT "FK_FACET_ATTRIBUTE_ID" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES
      "ATTRIBUTES" ("ATTRIBUTE_ID"),
     CONSTRAINT "FK_FACET_STATUS_ID" FOREIGN KEY ("STATUS_ID") REFERENCES
      "STATUS" ("STATUS_ID"),
     CONSTRAINT "FK_FACET_UPDATED_BY" FOREIGN KEY ("UPDATED_BY") REFERENCES
      "USERS" ("USER_ID"),
     CONSTRAINT "CHK_FACET_HIDDEN" CHECK(DISPLAY IN ('Y', 'N')),
     CONSTRAINT "CHK_FACET_DISPLAY_MODE" CHECK(DISPLAY_MODE IN ('SEARCH',
     'BROWSE', 'SEARCH_BROWSE')),
     CONSTRAINT "CHK_FACET_DIS_RECURRENCE" CHECK(DISPLAY_RECURRENCE IN ('Y', 'N')),
     CONSTRAINT "CHK_FACET_DIS_RMV_LNK" CHECK(DISPLAY_FACET_REMOVE_LNK IN ('Y', 'N')),
     CONSTRAINT "CHK_FACET_DIS_MOB_FACET" CHECK(DISPLAY_MOB_FACET IN ('Y', 'N')),
     CONSTRAINT "CHK_FACET_DIS_MOB_RMV_LNK" CHECK(DISPLAY_MOB_FACET_REMOVE_LNK IN ('Y', 'N')));  
 
  CREATE TABLE  "CONTEXT_FACETS"
  (
     "ATTRIBUTE_VALUE_ID"      NUMBER(19, 0),
     "FACET_ID" NUMBER(19, 0) NOT NULL,
     "CONTEXT_ID"       NUMBER(19, 0),
     "IS_ACTIVE"  NVARCHAR2(2) NOT NULL,
     CONSTRAINT "PK_CONTEXT_FACETS" PRIMARY KEY ("FACET_ID","CONTEXT_ID","ATTRIBUTE_VALUE_ID"),
     CONSTRAINT "FK_CTX_FACETS_CONTEXT_ID" FOREIGN KEY ("CONTEXT_ID") REFERENCES
      "CONTEXTS" ("CONTEXT_ID"),
     CONSTRAINT "FK_CTX_FACETS_FACET_ID" FOREIGN KEY ("FACET_ID") REFERENCES
      "FACETS" ("FACET_ID"),
       CONSTRAINT "FK_CTX_FACETS_ATTR_VAL_ID" FOREIGN KEY ("ATTRIBUTE_VALUE_ID") REFERENCES
      "ATTRIBUTE_VALUES" ("ATTRIBUTE_VALUE_ID")
  );  
  
CREATE TABLE  "CATEGORY_FACET"
  (
     "CAT_FACET_ID"            NUMBER(19, 0),
     "CATEGORY_NODE_ID"        NVARCHAR2(50),
     "DEP_FACET_ID"            NUMBER(19, 0),
     "DEP_FACET_ATTR_VALUE_ID" NUMBER(19, 0),
     "FACET_ID"                NUMBER(19, 0),
     "APPLY_SUB_CATEGORIES"    NVARCHAR2(1),
     "DEP_FACET_DISPLAY"       NVARCHAR2(1),
     "DISPLAY_ORDER"           NUMBER(8, 0),
     "DISPLAY"                 NVARCHAR2(1),
     "IS_ACTIVE"  			   NVARCHAR2(2),
     CONSTRAINT "PK_CATG_FACET" PRIMARY KEY ("CAT_FACET_ID"),
     CONSTRAINT "UC_CATEGORY_FACET" UNIQUE ("CATEGORY_NODE_ID", "FACET_ID",
     "DEP_FACET_ID"),
     CONSTRAINT "FK_CATG_FACET_FACET_ID" FOREIGN KEY ("FACET_ID") REFERENCES
      "FACETS" ("FACET_ID"),
     CONSTRAINT "FK_CATG_FACET_CATEGORY_NODE_ID" FOREIGN KEY ("CATEGORY_NODE_ID"
     ) REFERENCES  "CATEGORIES" ("CATEGORY_NODE_ID"),
     CONSTRAINT "FK_CATG_FACET_ATTR_VAL_ID" FOREIGN KEY (
     "DEP_FACET_ATTR_VALUE_ID") REFERENCES  "ATTRIBUTE_VALUES" (
     "ATTRIBUTE_VALUE_ID"),
     CONSTRAINT "CHK_CATG_FACET_DISPLAY" CHECK(DISPLAY IN ('Y', 'N')),
     CONSTRAINT "CHK_CATG_FACET_DEP_FACET_DSP" CHECK(DEP_FACET_DISPLAY IN ('Y',
     'N')),
     CONSTRAINT "CHK_CATG_APPLY_SUB_CATEGORIES" CHECK(APPLY_SUB_CATEGORIES IN (
     'Y', 'N')),
     CONSTRAINT "CHK_CATG_FACET_VALID" CHECK(IS_ACTIVE IN ('Y', 'N'))
  );  
     
     
   CREATE TABLE  "FACET_ATTR_VALUE_ORDER"
  (
     "FACET_ID"           NUMBER(19, 0) NOT NULL,
     "ATTRIBUTE_VALUE_ID" NUMBER(19, 0) NOT NULL,
     "DISPLAY_ORDER"      NUMBER(8, 0),
     "DO_NOT_DISPLAY"   NVARCHAR2(1) NOT NULL,
     CONSTRAINT "PK_FACET_ATTR_VAL_ORD" PRIMARY KEY ("FACET_ID",
     "ATTRIBUTE_VALUE_ID"),
     CONSTRAINT "FK_FACET_ATTR_FACET_ID" FOREIGN KEY ("FACET_ID") REFERENCES
      "FACETS" ("FACET_ID"),
     CONSTRAINT "FK_FACET_ATTR_ATTR_VAL_ID" FOREIGN KEY ("ATTRIBUTE_VALUE_ID")
     REFERENCES  "ATTRIBUTE_VALUES" ("ATTRIBUTE_VALUE_ID"),
     CONSTRAINT "CHK_FACET_ATTR_ATTR_VAL_DIS" CHECK("DO_NOT_DISPLAY" IN ('Y',
     'N'))
  );  
  
	CREATE TABLE BATCH_JOB_EXECUTION
  (
     JOB_EXECUTION_ID NUMBER PRIMARY KEY,
     JOB_INSTANCE_ID  NVARCHAR2(255) NOT NULL,
     START_TIME       DATE DEFAULT NULL,
     END_TIME         DATE DEFAULT NULL,
     STATUS           NVARCHAR2(255),
     EXIT_MESSAGE     NVARCHAR2(255),
     LAST_UPDATED     DATE
  );  

 CREATE TABLE  "PROMOS"
  (
    "PROMO_ID" NUMBER(19,0) NOT NULL,
    "PROMO_NAME" NVARCHAR2(150),
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE NOT NULL,
    "STATUS_ID" NUMBER(2,0),
    "CREATED_BY" NUMBER(19,0),
    "CREATED_DATE" DATE,
    "UPDATED_BY" NUMBER(19,0),
    "UPDATED_DATE" DATE,
    
  CONSTRAINT PK_PROMO PRIMARY KEY ("PROMO_ID") , 
  CONSTRAINT FK_PROMO_STATUS_ID_01 FOREIGN KEY ("STATUS_ID") REFERENCES  "STATUS" ("STATUS_ID"),
  CONSTRAINT FK_PROMO_UPDATED_BY_02 FOREIGN KEY ("UPDATED_BY") REFERENCES  "USERS" ("USER_ID"),
  CONSTRAINT FK_PROMO_CREATED_BY_03 FOREIGN KEY ("CREATED_BY") REFERENCES  "USERS" ("USER_ID")
 );
 



Create table  "PROMO_SKUS"
(
  "ID" NUMBER(19,0),
  "SKU_ID" NUMBER(19,0), 
  "PROMO_ID" NUMBER(19,0),
  
  CONSTRAINT PK_PROMO_SKUS PRIMARY KEY ("ID"),
  CONSTRAINT FK_PROMO_PROMO_ID_01 FOREIGN KEY ("PROMO_ID") REFERENCES  "PROMOS" ("PROMO_ID")
);


CREATE TABLE "KEYWORD_REDIRECTS"
  (
    "KEYWORD_ID" NUMBER(19,0) NOT NULL,
    "KEYWORD" NVARCHAR2(150),
    "REDIRECT_VALUE" NVARCHAR2(2000),
    "REDIRECT_TYPE" NVARCHAR2(10),
    "STATUS_ID" NUMBER(2,0),
    "SEARCH_PROFILE_ID" NUMBER(2,0),
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    "UPDATED_DATE" DATE,
    "UPDATED_BY" NUMBER(19,0),
    "CREATED_DATE" DATE,
    "CREATED_BY" NUMBER(19,0),
     
  CONSTRAINT KEYWORD_REDIRECTS PRIMARY KEY ("KEYWORD_ID") ,
  CONSTRAINT FK_KWD_REDIRECTS_STATUS_ID_01 FOREIGN KEY ("STATUS_ID") REFERENCES "STATUS" ("STATUS_ID"),
  CONSTRAINT FK_KWD_REDIRECTS_USER_ID_02 FOREIGN KEY ("UPDATED_BY") REFERENCES "USERS" ("USER_ID"),
  CONSTRAINT FK_KWD_REDIRECTS_USER_ID_03 FOREIGN KEY ("CREATED_BY") REFERENCES "USERS" ("USER_ID"),
  CONSTRAINT FK_KWD_RDTS_SRCH_PROF_ID_04 FOREIGN KEY ("SEARCH_PROFILE_ID") REFERENCES "SEARCH_PROFILES" ("SEARCH_PROFILE_ID")
 );
 
  CREATE TABLE "BOOSTS_AND_BLOCKS" 
   (	
    "ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TERM" NVARCHAR2(200) NOT NULL ENABLE, 
	"CATEGORY_ID" NVARCHAR2(25) NOT NULL ENABLE, 
	"SEARCH_PROFILE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATED_BY" NUMBER(20,0) NOT NULL ENABLE, 
	"CREATED_DATE" DATE, 
	"UPDATED_BY" NUMBER(20,0) NOT NULL ENABLE, 
	"UPDATED_DATE" DATE, 
	"STATUS_ID" NUMBER, 
	"START_DATE" DATE,
    "END_DATE" DATE,
	 CONSTRAINT "BOOSTS_AND_BLOCKS_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "FK1_BOOSTS_AND_BLOCKS" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORIES" ("CATEGORY_NODE_ID"), 
	 CONSTRAINT "FK2_BOOSTS_AND_BLOCKS" FOREIGN KEY ("SEARCH_PROFILE_ID")
	  REFERENCES "SEARCH_PROFILES" ("SEARCH_PROFILE_ID"), 
	 CONSTRAINT "FK3_BOOSTS_AND_BLOCKS" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "USERS" ("USER_ID"), 
	 CONSTRAINT "FK5_BOOSTS_AND_BLOCKS" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "STATUS" ("STATUS_ID"), 
	 CONSTRAINT "FK4_BOOSTS_AND_BLOCKS" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "USERS" ("USER_ID")
   ) ;
   
  CREATE TABLE "BOOSTS_AND_BLOCKS_PRODUCTS" 
   (	"ID" NUMBER(19,0), 
	"BOOST_AND_BLOCK_ID" NUMBER(19,0), 
	"PRODUCT_NAME" NVARCHAR2(200) NOT NULL, 
	"SKU_ID" NUMBER(19,0) NOT NULL, 
	"POSITION" NUMBER(2,0) NOT NULL, 
	 CONSTRAINT "PK_BOOSTS_AND_BLOCKS_PRODUCTS" PRIMARY KEY ("ID"), 
	 CONSTRAINT "FK_BOOST_AND_BLOCK_ID" FOREIGN KEY ("BOOST_AND_BLOCK_ID")
	 REFERENCES "BOOSTS_AND_BLOCKS" ("ID")
   );
 

  CREATE TABLE AF_BATCH_JOB_EXECUTION
  (
     JOB_EXECUTION_ID NUMBER(19,0),
     JOB_INSTANCE_ID  NVARCHAR2(255) NOT NULL,
     START_TIME       DATE DEFAULT NULL,
     END_TIME         DATE DEFAULT NULL,
     STATUS           NVARCHAR2(255),
     EXIT_MESSAGE     NVARCHAR2(255),
     LAST_UPDATED     DATE,
     CONSTRAINT "PK_AF_BATCH_JOB_EXECUTION" PRIMARY KEY ("JOB_EXECUTION_ID")
  );
  
  CREATE TABLE  "FACETS_DISPLAY_ORDER"
  (
 	 "ID" 					NUMBER(19,0),
     "CATEGORY_NODE_ID"     NVARCHAR2(50),
     "FACET_ID"             NUMBER(19, 0),
     "DISPLAY_ORDER"        NUMBER(8, 0),
     "STATUS_ID" 			NUMBER,
     CONSTRAINT "PK_FACETS_DISPLAY_ORDER" PRIMARY KEY ("ID"),
     CONSTRAINT "UK1_FACETS_DISPLAY_ORDER" UNIQUE ("CATEGORY_NODE_ID", "FACET_ID", "DISPLAY_ORDER"),
     CONSTRAINT "FK_FACET_ID" FOREIGN KEY ("FACET_ID")
     REFERENCES  "FACETS" ("FACET_ID") ENABLE,
     CONSTRAINT "FK_CATEGORY_NODE_ID" FOREIGN KEY ("CATEGORY_NODE_ID")
     REFERENCES  "CATEGORIES"("CATEGORY_NODE_ID") ENABLE,
     CONSTRAINT "FK_STATUS_ID" FOREIGN KEY ("STATUS_ID")
     REFERENCES  "STATUS"("STATUS_ID") ENABLE
  );
 
  CREATE TABLE "SKU_HISTORY" (
 	"ID" NUMBER(19,0), 
 	"SKU_ID" NVARCHAR2(50) NOT NULL ENABLE,
 	"ADDED_BY" NUMBER(10,0),
 	"ACTION" CHAR(1 BYTE),
 	"TIME" DATE,
	CONSTRAINT "PK_SKU_HISTORY" PRIMARY KEY ("ID"),
	CONSTRAINT "FK_SKU_HISTORY_ADDED_BY" FOREIGN KEY ("ADDED_BY")
	REFERENCES "USERS" ("USER_ID") ENABLE
  );
grant select on search.SKU_HISTORY to SEARCH_OBJSEL_ROLE;
grant select on search.STATUS to SEARCH_OBJSEL_ROLE;
grant select on search.ROLES to SEARCH_OBJSEL_ROLE;
grant select on search.USERS to SEARCH_OBJSEL_ROLE;
grant select on search.SYNONYM_TYPES to SEARCH_OBJSEL_ROLE;
grant select on search.SEARCH_PROFILES to SEARCH_OBJSEL_ROLE;
grant select on search.CATEGORIES to SEARCH_OBJSEL_ROLE;
grant select on search.CATEGORY_TREE to SEARCH_OBJSEL_ROLE;
grant select on search.ATTRIBUTES to SEARCH_OBJSEL_ROLE;
grant select on search.ATTRIBUTE_VALUES to SEARCH_OBJSEL_ROLE;
grant select on search.SYNONYMS to SEARCH_OBJSEL_ROLE;
grant select on search.SYNONYM_TERMS to SEARCH_OBJSEL_ROLE;
grant select on search.CONTEXTS to SEARCH_OBJSEL_ROLE;
grant select on search.CONTEXT_KEYWORDS to SEARCH_OBJSEL_ROLE;
grant select on search.BANNERS to SEARCH_OBJSEL_ROLE;
grant select on search.BANNER_CONTEXTS to SEARCH_OBJSEL_ROLE;
grant select on search.BANNER_TEMPLATE_META to SEARCH_OBJSEL_ROLE;
grant select on search.BANNER_TEMPLATES to SEARCH_OBJSEL_ROLE;
grant select on search.FACETS to SEARCH_OBJSEL_ROLE;
grant select on search.CONTEXT_FACETS to SEARCH_OBJSEL_ROLE;
grant select on search.CATEGORY_FACET to SEARCH_OBJSEL_ROLE;
grant select on search.FACET_ATTR_VALUE_ORDER to SEARCH_OBJSEL_ROLE;
grant select on search.BATCH_JOB_EXECUTION to SEARCH_OBJSEL_ROLE;
grant select on search.PROMOS to SEARCH_OBJSEL_ROLE;
grant select on search.PROMO_SKUS to SEARCH_OBJSEL_ROLE;
grant select on search.KEYWORD_REDIRECTS to SEARCH_OBJSEL_ROLE;
grant select on search.BOOSTS_AND_BLOCKS to SEARCH_OBJSEL_ROLE;
grant select on search.BOOSTS_AND_BLOCKS_PRODUCTS to SEARCH_OBJSEL_ROLE;
grant select on search.AF_BATCH_JOB_EXECUTION to SEARCH_OBJSEL_ROLE;
grant select on search.FACETS_DISPLAY_ORDER to SEARCH_OBJSEL_ROLE;

grant select,insert,update,delete on search.SKU_HISTORY to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.STATUS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.ROLES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.USERS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.SYNONYM_TYPES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.SEARCH_PROFILES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.CATEGORIES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.CATEGORY_TREE to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.ATTRIBUTES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.ATTRIBUTE_VALUES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.SYNONYMS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.SYNONYM_TERMS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.CONTEXTS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.CONTEXT_KEYWORDS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BANNERS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BANNER_CONTEXTS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BANNER_TEMPLATE_META to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BANNER_TEMPLATES to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.FACETS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.CONTEXT_FACETS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.CATEGORY_FACET to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.FACET_ATTR_VALUE_ORDER to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BATCH_JOB_EXECUTION to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.PROMOS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.PROMO_SKUS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.KEYWORD_REDIRECTS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BOOSTS_AND_BLOCKS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.BOOSTS_AND_BLOCKS_PRODUCTS to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.AF_BATCH_JOB_EXECUTION to SEARCH_OBJUPD_ROLE;
grant select,insert,update,delete on search.FACETS_DISPLAY_ORDER to SEARCH_OBJUPD_ROLE;

--conn searchadmin
create synonym searchadmin.SKU_HISTORY for search.SKU_HISTORY;
create synonym searchadmin.STATUS for search.STATUS;
create synonym searchadmin.ROLES for search.ROLES;
create synonym searchadmin.USERS for search.USERS;
create synonym searchadmin.SYNONYM_TYPES for search.SYNONYM_TYPES;
create synonym searchadmin.SEARCH_PROFILES for search.SEARCH_PROFILES;
create synonym searchadmin.CATEGORIES for search.CATEGORIES;
create synonym searchadmin.CATEGORY_TREE for search.CATEGORY_TREE;
create synonym searchadmin.ATTRIBUTES for search.ATTRIBUTES;
create synonym searchadmin.ATTRIBUTE_VALUES for search.ATTRIBUTE_VALUES;
create synonym searchadmin.SYNONYMS for search.SYNONYMS;
create synonym searchadmin.SYNONYM_TERMS for search.SYNONYM_TERMS;
create synonym searchadmin.CONTEXTS for search.CONTEXTS;
create synonym searchadmin.CONTEXT_KEYWORDS for search.CONTEXT_KEYWORDS;
create synonym searchadmin.BANNERS for search.BANNERS;
create synonym searchadmin.BANNER_CONTEXTS for search.BANNER_CONTEXTS;
create synonym searchadmin.BANNER_TEMPLATE_META for search.BANNER_TEMPLATE_META;
create synonym searchadmin.BANNER_TEMPLATES for search.BANNER_TEMPLATES;
create synonym searchadmin.FACETS for search.FACETS;
create synonym searchadmin.CONTEXT_FACETS for search.CONTEXT_FACETS;
create synonym searchadmin.CATEGORY_FACET for search.CATEGORY_FACET;
create synonym searchadmin.FACET_ATTR_VALUE_ORDER for search.FACET_ATTR_VALUE_ORDER;
create synonym searchadmin.BATCH_JOB_EXECUTION for search.BATCH_JOB_EXECUTION;
create synonym searchadmin.PROMOS for search.PROMOS;
create synonym searchadmin.PROMO_SKUS for search.PROMO_SKUS;
create synonym searchadmin.KEYWORD_REDIRECTS for search.KEYWORD_REDIRECTS;
create synonym searchadmin.BOOSTS_AND_BLOCKS for search.BOOSTS_AND_BLOCKS;
create synonym searchadmin.BOOSTS_AND_BLOCKS_PRODUCTS for search.BOOSTS_AND_BLOCKS_PRODUCTS;
create synonym searchadmin.AF_BATCH_JOB_EXECUTION for search.AF_BATCH_JOB_EXECUTION;
create synonym searchadmin.FACETS_DISPLAY_ORDER for search.FACETS_DISPLAY_ORDER;
create synonym searchadmin.FACETS_DISPLAY_ORDER for search.FACETS_DISPLAY_ORDER;

commit;
