--Synonyms
	CREATE INDEX IDX_SYNONYMS_01 ON SYNONYMS (UPPER(PRIMARY_TERM), UPDATED_BY, STATUS_ID);
	CREATE INDEX IDX_SYNONYMS_02 ON SYNONYMS (UPDATED_DATE,STATUS_ID);
	CREATE INDEX IDX_SYNONYMS_03 ON SYNONYMS (STATUS_ID,UPDATED_DATE);
	CREATE INDEX IDX_SYNONYMS_04 ON SYNONYMS (UPPER(DIRECTIONALITY), UPDATED_BY, STATUS_ID);
	CREATE INDEX IDX_SYNONYMS_05 ON SYNONYMS (UPPER(MATCH_TYPE), UPDATED_BY, STATUS_ID);
	CREATE INDEX IDX_SYNONYMS_06 ON SYNONYMS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	
	CREATE INDEX IDX_SYNONYM_TERMS_01 ON SYNONYM_TERMS (TERM);


--Keyword Redirects
	CREATE INDEX IDX_KEYWORD_REDIRECTS_01 ON KEYWORD_REDIRECTS (UPPER(KEYWORD), UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_KEYWORD_REDIRECTS_02 ON KEYWORD_REDIRECTS (UPPER(REDIRECT_VALUE),UPDATED_DATE , STATUS_ID);
	CREATE INDEX IDX_KEYWORD_REDIRECTS_03 ON KEYWORD_REDIRECTS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_KEYWORD_REDIRECTS_04 ON KEYWORD_REDIRECTS (STATUS_ID,UPDATED_DATE);
	CREATE INDEX IDX_KEYWORD_REDIRECTS_05 ON KEYWORD_REDIRECTS (UPDATED_DATE,STATUS_ID);
	CREATE INDEX IDX_KEYWORD_REDIRECTS_06 ON KEYWORD_REDIRECTS (START_DATE, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_KEYWORD_REDIRECTS_07 ON KEYWORD_REDIRECTS (END_DATE, UPDATED_DATE, STATUS_ID);

--Banners
	CREATE INDEX IDX_BANNERS_01 ON BANNERS (UPPER(BANNER_NAME), UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BANNERS_02 ON BANNERS (UPPER(BANNER_TYPE), UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BANNERS_03 ON BANNERS (UPPER(BANNER_PRIORITY), UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BANNERS_04 ON BANNERS (START_DATE, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BANNERS_05 ON BANNERS (END_DATE, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BANNERS_06 ON BANNERS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BANNERS_07 ON BANNERS (UPDATED_DATE, STATUS_ID); 
	CREATE INDEX IDX_BANNERS_08 ON BANNERS (STATUS_ID, UPDATED_DATE);

--Promo
	CREATE INDEX IDX_PROMOS_01 ON PROMOS (UPPER(PROMO_NAME), UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_PROMOS_02 ON PROMOS (UPDATED_DATE,STATUS_ID);
	CREATE INDEX IDX_PROMOS_03 ON PROMOS (STATUS_ID,UPDATED_DATE);
	CREATE INDEX IDX_PROMOS_04 ON PROMOS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_PROMOS_05 ON PROMOS (START_DATE, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_PROMOS_06 ON PROMOS (END_DATE, UPDATED_DATE, STATUS_ID);
	
	CREATE INDEX IDX_PROMO_SKUS_01 ON PROMO_SKUS (SKU_ID);

--Facets
	CREATE INDEX IDX_FACETS_01 ON FACETS (UPPER(DISPLAY_NAME), UPPER(SYSTEM_NAME),UPDATED_BY, STATUS_ID);
	CREATE INDEX IDX_FACETS_02 ON FACETS (STATUS_ID, UPDATED_DATE);
	CREATE INDEX IDX_FACETS_03 ON FACETS (UPDATED_DATE,STATUS_ID);
	CREATE INDEX IDX_FACETS_04 ON FACETS (START_DATE, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_FACETS_05 ON FACETS (END_DATE, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_FACETS_06 ON FACETS (UPDATED_BY, UPDATED_DATE, STATUS_ID);

--BoostAndBlock
	CREATE INDEX IDX_BOOSTS_AND_BLOCKS_01 ON BOOSTS_AND_BLOCKS (UPPER(TERM), UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BOOSTS_AND_BLOCKS_02 ON BOOSTS_AND_BLOCKS (SEARCH_PROFILE_ID, STATUS_ID);
	CREATE INDEX IDX_BOOSTS_AND_BLOCKS_03 ON BOOSTS_AND_BLOCKS (CATEGORY_ID, UPDATED_DATE, STATUS_ID);
	CREATE INDEX IDX_BOOSTS_AND_BLOCKS_04 ON BOOSTS_AND_BLOCKS (UPDATED_DATE,STATUS_ID);
	CREATE INDEX IDX_BOOSTS_AND_BLOCKS_05 ON BOOSTS_AND_BLOCKS (STATUS_ID, UPDATED_DATE);
	CREATE INDEX IDX_BOOSTS_AND_BLOCKS_06 ON BOOSTS_AND_BLOCKS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	
	commit;