insert into status values (10, 'Published AF');
update status set status_name='Published CF' where status_id=8;

NOTE: TAKE BACKUP OF DATA IN ALL TABLES BEFORE EXECUTING THE BELOW SQL STATEMENTS AND INSERT THEM BACK ONCE THE SCRIPTS SUCCESSFULLY RUN

DELETE FROM SKU_HISTORY;
DELETE FROM FACETS_DISPLAY_ORDER;
DELETE FROM AF_BATCH_JOB_EXECUTION;
DELETE FROM BOOSTS_AND_BLOCKS_PRODUCTS;
DELETE FROM BOOSTS_AND_BLOCKS;
DELETE FROM KEYWORD_REDIRECTS;
DELETE FROM PROMO_SKUS;
DELETE FROM PROMOS;
DELETE FROM BATCH_JOB_EXECUTION;
DELETE FROM FACET_ATTR_VALUE_ORDER;
DELETE FROM CATEGORY_FACET;
DELETE FROM CONTEXT_FACETS;
DELETE FROM FACETS;
DELETE FROM BANNER_TEMPLATES;
DELETE FROM BANNER_TEMPLATE_META;
DELETE FROM BANNER_CONTEXTS;
DELETE FROM BANNERS;
DELETE FROM CONTEXT_KEYWORDS;
DELETE FROM CONTEXTS;
DELETE FROM SYNONYM_TERMS;
DELETE FROM SYNONYMS;
DELETE FROM ATTRIBUTE_VALUES;
DELETE FROM ATTRIBUTES;
DELETE FROM CATEGORY_TREE;
DELETE FROM CATEGORIES;
DELETE FROM SEARCH_PROFILES;
DELETE FROM SYNONYM_TYPES;
DELETE FROM USERS;
DELETE FROM ROLES;
DELETE FROM STATUS;

DROP INDEX IDX_SYNONYMS_01;
DROP INDEX IDX_SYNONYMS_02;
DROP INDEX IDX_SYNONYMS_03;
DROP INDEX IDX_SYNONYMS_04;
DROP INDEX IDX_SYNONYMS_05;
DROP INDEX IDX_SYNONYMS_06;
DROP INDEX IDX_SYNONYM_TERMS_01;
DROP INDEX IDX_KEYWORD_REDIRECTS_01;
DROP INDEX IDX_KEYWORD_REDIRECTS_02;
DROP INDEX IDX_KEYWORD_REDIRECTS_03;
DROP INDEX IDX_KEYWORD_REDIRECTS_04;
DROP INDEX IDX_KEYWORD_REDIRECTS_05;
DROP INDEX IDX_KEYWORD_REDIRECTS_06;
DROP INDEX IDX_KEYWORD_REDIRECTS_07;
DROP INDEX IDX_BANNERS_01;
DROP INDEX IDX_BANNERS_02;
DROP INDEX IDX_BANNERS_03;
DROP INDEX IDX_BANNERS_04;
DROP INDEX IDX_BANNERS_05;
DROP INDEX IDX_BANNERS_06;
DROP INDEX IDX_BANNERS_07; 
DROP INDEX IDX_BANNERS_08;
DROP INDEX IDX_PROMOS_01;
DROP INDEX IDX_PROMOS_02;
DROP INDEX IDX_PROMOS_03;
DROP INDEX IDX_PROMOS_04;
DROP INDEX IDX_PROMOS_05;
DROP INDEX IDX_PROMOS_06;	
DROP INDEX IDX_PROMO_SKUS_01;
DROP INDEX IDX_FACETS_01;
DROP INDEX IDX_FACETS_02;
DROP INDEX IDX_FACETS_03;
DROP INDEX IDX_FACETS_04;
DROP INDEX IDX_FACETS_05;
DROP INDEX IDX_FACETS_06;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_01;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_02;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_03;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_04;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_05;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_06;

ALTER TABLE STATUS MODIFY STATUS_NAME NVARCHAR2(15);

ALTER TABLE ROLES MODIFY NAME NVARCHAR2(20);
ALTER TABLE ROLES MODIFY DESCRIPTION NVARCHAR2(40);

ALTER TABLE USERS MODIFY EMAIL NVARCHAR2(255);
ALTER TABLE USERS MODIFY FIRST_NAME NVARCHAR2(255);
ALTER TABLE USERS MODIFY LAST_NAME NVARCHAR2(255);
ALTER TABLE USERS MODIFY LOGIN_NAME NVARCHAR2(255);
ALTER TABLE USERS MODIFY PASSWORD NVARCHAR2(255);
ALTER TABLE USERS MODIFY UPDATED_BY NVARCHAR2(255);

ALTER TABLE SYNONYM_TYPES MODIFY NAME NVARCHAR2(255);

ALTER TABLE SEARCH_PROFILES MODIFY COLLECTIONS NVARCHAR2(255);
ALTER TABLE SEARCH_PROFILES MODIFY DEFAULT_PATH NVARCHAR2(255);
ALTER TABLE SEARCH_PROFILES MODIFY LASTMODIFIER_ID NVARCHAR2(20);
ALTER TABLE SEARCH_PROFILES MODIFY PIPELINE_NAME NVARCHAR2(255);
ALTER TABLE SEARCH_PROFILES MODIFY PROFILE_NAME NVARCHAR2(255);
ALTER TABLE SEARCH_PROFILES MODIFY RANK_PROFILE_NAME NVARCHAR2(255);
ALTER TABLE SEARCH_PROFILES MODIFY SEARCH_FIELD_NAME NVARCHAR2(255);
ALTER TABLE SEARCH_PROFILES MODIFY TOP_CATEGORY_ID NVARCHAR2(255);

ALTER TABLE CATEGORIES MODIFY CATEGORY_NODE_ID NVARCHAR2(25);
ALTER TABLE CATEGORIES MODIFY CATEGORY_PATH NVARCHAR2(255);
ALTER TABLE CATEGORIES MODIFY IS_ACTIVE NVARCHAR2(2);
ALTER TABLE CATEGORIES MODIFY ALSO_FOUND NVARCHAR2(2000);

ALTER TABLE CATEGORY_TREE DROP COLUMN CATEGORY_TREE;
ALTER TABLE CATEGORY_TREE ADD CATEGORY_TREE NCLOB;

ALTER TABLE ATTRIBUTES MODIFY ATTRIBUTE_NAME NVARCHAR2(255);
ALTER TABLE ATTRIBUTES MODIFY IS_ACTIVE NVARCHAR2(2);

ALTER TABLE ATTRIBUTE_VALUES MODIFY ATTRIBUTE_VALUE NVARCHAR2(255);
ALTER TABLE ATTRIBUTE_VALUES MODIFY IS_ACTIVE NVARCHAR2(2);

ALTER TABLE SYNONYMS MODIFY DIRECTIONALITY NVARCHAR2(20);
ALTER TABLE SYNONYMS MODIFY MATCH_TYPE NVARCHAR2(20);
ALTER TABLE SYNONYMS MODIFY PRIMARY_TERM NVARCHAR2(255);
ALTER TABLE SYNONYMS MODIFY NAME NVARCHAR2(255);

ALTER TABLE SYNONYM_TERMS MODIFY TERM NVARCHAR2(200);

ALTER TABLE CONTEXTS MODIFY CATEGORY_NODE_ID NVARCHAR2(50);
ALTER TABLE CONTEXTS MODIFY IS_ACTIVE NVARCHAR2(2);

ALTER TABLE CONTEXT_KEYWORDS MODIFY KEYWORD NVARCHAR2(255);

ALTER TABLE BANNERS MODIFY BANNER_NAME NVARCHAR2(255);
ALTER TABLE BANNERS MODIFY BANNER_TEMPLATE NVARCHAR2(255);

ALTER TABLE BANNER_TEMPLATE_META MODIFY BANNER_TEMPLATE_FIELD_LIST NVARCHAR2(255);
ALTER TABLE BANNER_TEMPLATE_META MODIFY BANNER_TEMPLATE_NAME NVARCHAR2(255);

ALTER TABLE BANNER_TEMPLATES MODIFY TEMPLATE_TYPE NVARCHAR2(15);
ALTER TABLE BANNER_TEMPLATES MODIFY TEMPLATE_HEADER NVARCHAR2(255);
ALTER TABLE BANNER_TEMPLATES MODIFY SKUS NVARCHAR2(255);

ALTER TABLE FACETS MODIFY DISPLAY_NAME NVARCHAR2(100);
ALTER TABLE FACETS MODIFY SYSTEM_NAME NVARCHAR2(100);
ALTER TABLE FACETS MODIFY DISPLAY_MODE NVARCHAR2(15);
ALTER TABLE FACETS MODIFY DISPLAY NVARCHAR2(1);
ALTER TABLE FACETS MODIFY DISPLAY_RECURRENCE NVARCHAR2(1);
ALTER TABLE FACETS MODIFY DISPLAY_FACET_REMOVE_LNK NVARCHAR2(1);
ALTER TABLE FACETS MODIFY DISPLAY_MOB_FACET NVARCHAR2(1);
ALTER TABLE FACETS MODIFY DISPLAY_MOB_FACET_REMOVE_LNK NVARCHAR2(1);
ALTER TABLE FACETS MODIFY SORT_TYPE NVARCHAR2(18);
ALTER TABLE FACETS MODIFY POSITION NVARCHAR2(10);

ALTER TABLE CONTEXT_FACETS MODIFY IS_ACTIVE NVARCHAR2(2);

ALTER TABLE CATEGORY_FACET MODIFY CATEGORY_NODE_ID NVARCHAR2(50);
ALTER TABLE CATEGORY_FACET MODIFY APPLY_SUB_CATEGORIES NVARCHAR2(1);
ALTER TABLE CATEGORY_FACET MODIFY DEP_FACET_DISPLAY NVARCHAR2(1);
ALTER TABLE CATEGORY_FACET MODIFY DISPLAY NVARCHAR2(1);
ALTER TABLE CATEGORY_FACET MODIFY IS_ACTIVE NVARCHAR2(2);

ALTER TABLE FACET_ATTR_VALUE_ORDER MODIFY DO_NOT_DISPLAY NVARCHAR2(1);

ALTER TABLE BATCH_JOB_EXECUTION MODIFY JOB_INSTANCE_ID NVARCHAR2(255);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY STATUS NVARCHAR2(255);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY EXIT_MESSAGE NVARCHAR2(255);

ALTER TABLE PROMOS MODIFY PROMO_NAME NVARCHAR2(150);

ALTER TABLE KEYWORD_REDIRECTS MODIFY KEYWORD NVARCHAR2(150);
ALTER TABLE KEYWORD_REDIRECTS MODIFY REDIRECT_VALUE NVARCHAR2(2000);
ALTER TABLE KEYWORD_REDIRECTS MODIFY REDIRECT_TYPE NVARCHAR2(10);

ALTER TABLE BOOSTS_AND_BLOCKS MODIFY TERM NVARCHAR2(200);
ALTER TABLE BOOSTS_AND_BLOCKS MODIFY CATEGORY_ID NVARCHAR2(25);

ALTER TABLE BOOSTS_AND_BLOCKS_PRODUCTS MODIFY PRODUCT_NAME NVARCHAR2(200);

ALTER TABLE AF_BATCH_JOB_EXECUTION MODIFY JOB_INSTANCE_ID NVARCHAR2(255);
ALTER TABLE AF_BATCH_JOB_EXECUTION MODIFY STATUS NVARCHAR2(255);
ALTER TABLE AF_BATCH_JOB_EXECUTION MODIFY EXIT_MESSAGE NVARCHAR2(255);

ALTER TABLE FACETS_DISPLAY_ORDER MODIFY CATEGORY_NODE_ID NVARCHAR2(50);

ALTER TABLE SKU_HISTORY MODIFY SKU_ID NVARCHAR2(50);

CREATE INDEX IDX_SYNONYMS_01 ON SYNONYMS (UPPER(PRIMARY_TERM), UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_SYNONYMS_02 ON SYNONYMS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_SYNONYMS_03 ON SYNONYMS (STATUS_ID,UPDATED_DATE);
CREATE INDEX IDX_SYNONYMS_04 ON SYNONYMS (UPPER(DIRECTIONALITY), UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_SYNONYMS_05 ON SYNONYMS (UPPER(MATCH_TYPE), UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_SYNONYMS_06 ON SYNONYMS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	
CREATE INDEX IDX_SYNONYM_TERMS_01 ON SYNONYM_TERMS (TERM);

CREATE INDEX IDX_KEYWORD_REDIRECTS_01 ON KEYWORD_REDIRECTS (UPPER(KEYWORD), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_02 ON KEYWORD_REDIRECTS (UPPER(REDIRECT_VALUE),UPDATED_DATE , STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_03 ON KEYWORD_REDIRECTS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_04 ON KEYWORD_REDIRECTS (STATUS_ID,UPDATED_DATE);
CREATE INDEX IDX_KEYWORD_REDIRECTS_05 ON KEYWORD_REDIRECTS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_06 ON KEYWORD_REDIRECTS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_07 ON KEYWORD_REDIRECTS (END_DATE, UPDATED_DATE, STATUS_ID);

CREATE INDEX IDX_BANNERS_01 ON BANNERS (UPPER(BANNER_NAME), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_02 ON BANNERS (UPPER(BANNER_TYPE), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_03 ON BANNERS (UPPER(BANNER_PRIORITY), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_04 ON BANNERS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_05 ON BANNERS (END_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_06 ON BANNERS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_07 ON BANNERS (UPDATED_DATE, STATUS_ID); 
CREATE INDEX IDX_BANNERS_08 ON BANNERS (STATUS_ID, UPDATED_DATE);

CREATE INDEX IDX_PROMOS_01 ON PROMOS (UPPER(PROMO_NAME), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_PROMOS_02 ON PROMOS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_PROMOS_03 ON PROMOS (STATUS_ID,UPDATED_DATE);
CREATE INDEX IDX_PROMOS_04 ON PROMOS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_PROMOS_05 ON PROMOS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_PROMOS_06 ON PROMOS (END_DATE, UPDATED_DATE, STATUS_ID);
	
CREATE INDEX IDX_PROMO_SKUS_01 ON PROMO_SKUS (SKU_ID);

CREATE INDEX IDX_FACETS_01 ON FACETS (UPPER(DISPLAY_NAME), UPPER(SYSTEM_NAME),UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_FACETS_02 ON FACETS (STATUS_ID, UPDATED_DATE);
CREATE INDEX IDX_FACETS_03 ON FACETS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_FACETS_04 ON FACETS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_FACETS_05 ON FACETS (END_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_FACETS_06 ON FACETS (UPDATED_BY, UPDATED_DATE, STATUS_ID);

CREATE INDEX IDX_BOOSTS_AND_BLOCKS_01 ON BOOSTS_AND_BLOCKS (UPPER(TERM), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_02 ON BOOSTS_AND_BLOCKS (SEARCH_PROFILE_ID, STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_03 ON BOOSTS_AND_BLOCKS (CATEGORY_ID, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_04 ON BOOSTS_AND_BLOCKS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_05 ON BOOSTS_AND_BLOCKS (STATUS_ID, UPDATED_DATE);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_06 ON BOOSTS_AND_BLOCKS (UPDATED_BY, UPDATED_DATE, STATUS_ID);

commit;