delete from synonym_terms where synonym_id in (select id from synonyms where status_id=10);
delete from synonyms where status_id=10;

delete from banner_templates where banner_id in (select banner_id from banners where status_id=10);
delete from banner_contexts where banner_id in (select banner_id from banners where status_id=10);
delete from banners where status_id=10;

delete from facets_display_order where facet_id in (select facet_id from facets where status_id=10);
delete from facet_attr_value_order where facet_id in (select facet_id from facets where status_id=10);
delete from category_facet where facet_id in (select facet_id from facets where status_id=10);
delete from context_facets where facet_id in (select facet_id from facets where status_id=10);
delete from facets where status_id=10;

delete from promo_skus where promo_id in (select promo_id from promos where status_id=10);
delete from promos where status_id=10;

delete from keyword_redirects where status_id=10;

delete from boosts_and_blocks_products where boost_and_block_id in (select id from boosts_and_blocks where status_id=10);
delete from boosts_and_blocks where status_id=10;

delete from facets_display_order where status_id=10;

delete from status where status_id=10;
update status set status_name='Published' where status_id=8;

NOTE: TAKE BACKUP OF DATA IN ALL TABLES BEFORE EXECUTING THE BELOW SQL STATEMENTS AND INSERT THEM BACK ONCE THE SCRIPTS SUCCESSFULLY RUN

DELETE FROM SKU_HISTORY;
DELETE FROM FACETS_DISPLAY_ORDER;
DELETE FROM AF_BATCH_JOB_EXECUTION;
DELETE FROM BOOSTS_AND_BLOCKS_PRODUCTS;
DELETE FROM BOOSTS_AND_BLOCKS;
DELETE FROM KEYWORD_REDIRECTS;
DELETE FROM PROMO_SKUS;
DELETE FROM PROMOS;
DELETE FROM BATCH_JOB_EXECUTION;
DELETE FROM FACET_ATTR_VALUE_ORDER;
DELETE FROM CATEGORY_FACET;
DELETE FROM CONTEXT_FACETS;
DELETE FROM FACETS;
DELETE FROM BANNER_TEMPLATES;
DELETE FROM BANNER_TEMPLATE_META;
DELETE FROM BANNER_CONTEXTS;
DELETE FROM BANNERS;
DELETE FROM CONTEXT_KEYWORDS;
DELETE FROM CONTEXTS;
DELETE FROM SYNONYM_TERMS;
DELETE FROM SYNONYMS;
DELETE FROM ATTRIBUTE_VALUES;
DELETE FROM ATTRIBUTES;
DELETE FROM CATEGORY_TREE;
DELETE FROM CATEGORIES;
DELETE FROM SEARCH_PROFILES;
DELETE FROM SYNONYM_TYPES;
DELETE FROM USERS;
DELETE FROM ROLES;
DELETE FROM STATUS;

DROP INDEX IDX_SYNONYMS_01;
DROP INDEX IDX_SYNONYMS_02;
DROP INDEX IDX_SYNONYMS_03;
DROP INDEX IDX_SYNONYMS_04;
DROP INDEX IDX_SYNONYMS_05;
DROP INDEX IDX_SYNONYMS_06;
DROP INDEX IDX_SYNONYM_TERMS_01;
DROP INDEX IDX_KEYWORD_REDIRECTS_01;
DROP INDEX IDX_KEYWORD_REDIRECTS_02;
DROP INDEX IDX_KEYWORD_REDIRECTS_03;
DROP INDEX IDX_KEYWORD_REDIRECTS_04;
DROP INDEX IDX_KEYWORD_REDIRECTS_05;
DROP INDEX IDX_KEYWORD_REDIRECTS_06;
DROP INDEX IDX_KEYWORD_REDIRECTS_07;
DROP INDEX IDX_BANNERS_01;
DROP INDEX IDX_BANNERS_02;
DROP INDEX IDX_BANNERS_03;
DROP INDEX IDX_BANNERS_04;
DROP INDEX IDX_BANNERS_05;
DROP INDEX IDX_BANNERS_06;
DROP INDEX IDX_BANNERS_07; 
DROP INDEX IDX_BANNERS_08;
DROP INDEX IDX_PROMOS_01;
DROP INDEX IDX_PROMOS_02;
DROP INDEX IDX_PROMOS_03;
DROP INDEX IDX_PROMOS_04;
DROP INDEX IDX_PROMOS_05;
DROP INDEX IDX_PROMOS_06;	
DROP INDEX IDX_PROMO_SKUS_01;
DROP INDEX IDX_FACETS_01;
DROP INDEX IDX_FACETS_02;
DROP INDEX IDX_FACETS_03;
DROP INDEX IDX_FACETS_04;
DROP INDEX IDX_FACETS_05;
DROP INDEX IDX_FACETS_06;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_01;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_02;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_03;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_04;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_05;
DROP INDEX IDX_BOOSTS_AND_BLOCKS_06;

ALTER TABLE STATUS MODIFY STATUS_NAME VARCHAR2(15 BYTE);

ALTER TABLE ROLES MODIFY NAME VARCHAR2(20 BYTE);
ALTER TABLE ROLES MODIFY DESCRIPTION VARCHAR2(40 BYTE);

ALTER TABLE USERS MODIFY EMAIL VARCHAR2(255 BYTE);
ALTER TABLE USERS MODIFY FIRST_NAME VARCHAR2(255 BYTE);
ALTER TABLE USERS MODIFY LAST_NAME VARCHAR2(255 BYTE);
ALTER TABLE USERS MODIFY LOGIN_NAME VARCHAR2(255 BYTE);
ALTER TABLE USERS MODIFY PASSWORD VARCHAR2(255 BYTE);
ALTER TABLE USERS MODIFY UPDATED_BY VARCHAR2(255 BYTE);

ALTER TABLE SYNONYM_TYPES MODIFY NAME VARCHAR2(255 BYTE);

ALTER TABLE SEARCH_PROFILES MODIFY COLLECTIONS VARCHAR2(255 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY DEFAULT_PATH VARCHAR2(255 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY LASTMODIFIER_ID VARCHAR2(20 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY PIPELINE_NAME VARCHAR2(255 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY PROFILE_NAME VARCHAR2(255 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY RANK_PROFILE_NAME VARCHAR2(255 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY SEARCH_FIELD_NAME VARCHAR2(255 BYTE);
ALTER TABLE SEARCH_PROFILES MODIFY TOP_CATEGORY_ID VARCHAR2(255 BYTE);

ALTER TABLE CATEGORIES MODIFY CATEGORY_NODE_ID VARCHAR2(25 BYTE);
ALTER TABLE CATEGORIES MODIFY CATEGORY_PATH VARCHAR2(255 BYTE);
ALTER TABLE CATEGORIES MODIFY IS_ACTIVE VARCHAR2(2 BYTE);
ALTER TABLE CATEGORIES MODIFY ALSO_FOUND VARCHAR2(2000 BYTE);

ALTER TABLE CATEGORY_TREE DROP COLUMN CATEGORY_TREE;
ALTER TABLE CATEGORY_TREE ADD CATEGORY_TREE CLOB;

ALTER TABLE ATTRIBUTES MODIFY ATTRIBUTE_NAME VARCHAR2(255 BYTE);
ALTER TABLE ATTRIBUTES MODIFY IS_ACTIVE VARCHAR2(2 BYTE);

ALTER TABLE ATTRIBUTE_VALUES MODIFY ATTRIBUTE_VALUE VARCHAR2(255 BYTE);
ALTER TABLE ATTRIBUTE_VALUES MODIFY IS_ACTIVE VARCHAR2(2 BYTE);

ALTER TABLE SYNONYMS MODIFY DIRECTIONALITY VARCHAR2(20 BYTE);
ALTER TABLE SYNONYMS MODIFY MATCH_TYPE VARCHAR2(20 BYTE);
ALTER TABLE SYNONYMS MODIFY PRIMARY_TERM VARCHAR2(255 CHAR);
ALTER TABLE SYNONYMS MODIFY NAME VARCHAR2(255 CHAR);

ALTER TABLE SYNONYM_TERMS MODIFY TERM VARCHAR2(200 BYTE);

ALTER TABLE CONTEXTS MODIFY CATEGORY_NODE_ID VARCHAR2(50 CHAR);
ALTER TABLE CONTEXTS MODIFY IS_ACTIVE VARCHAR2(2 BYTE);

ALTER TABLE CONTEXT_KEYWORDS MODIFY KEYWORD VARCHAR2(255 BYTE);

ALTER TABLE BANNERS MODIFY BANNER_NAME VARCHAR2(255 BYTE);
ALTER TABLE BANNERS MODIFY BANNER_TEMPLATE VARCHAR2(255 BYTE);

ALTER TABLE BANNER_TEMPLATE_META MODIFY BANNER_TEMPLATE_FIELD_LIST VARCHAR2(255 BYTE);
ALTER TABLE BANNER_TEMPLATE_META MODIFY BANNER_TEMPLATE_NAME VARCHAR2(255 BYTE);

ALTER TABLE BANNER_TEMPLATES MODIFY TEMPLATE_TYPE VARCHAR2(15 BYTE);
ALTER TABLE BANNER_TEMPLATES MODIFY TEMPLATE_HEADER VARCHAR2(255 BYTE);
ALTER TABLE BANNER_TEMPLATES MODIFY SKUS VARCHAR2(255 BYTE);

ALTER TABLE FACETS MODIFY DISPLAY_NAME VARCHAR2(100 BYTE);
ALTER TABLE FACETS MODIFY SYSTEM_NAME VARCHAR2(100 BYTE);
ALTER TABLE FACETS MODIFY DISPLAY_MODE VARCHAR2(15 BYTE);
ALTER TABLE FACETS MODIFY DISPLAY VARCHAR2(1 BYTE);
ALTER TABLE FACETS MODIFY DISPLAY_RECURRENCE VARCHAR2(1 BYTE);
ALTER TABLE FACETS MODIFY DISPLAY_FACET_REMOVE_LNK VARCHAR2(1 BYTE);
ALTER TABLE FACETS MODIFY DISPLAY_MOB_FACET VARCHAR2(1 BYTE);
ALTER TABLE FACETS MODIFY DISPLAY_MOB_FACET_REMOVE_LNK VARCHAR2(1 BYTE);
ALTER TABLE FACETS MODIFY SORT_TYPE VARCHAR2(18 BYTE);
ALTER TABLE FACETS MODIFY POSITION VARCHAR2(10 BYTE);

ALTER TABLE CONTEXT_FACETS MODIFY IS_ACTIVE VARCHAR2(2 BYTE);

ALTER TABLE CATEGORY_FACET MODIFY CATEGORY_NODE_ID VARCHAR2(50 CHAR);
ALTER TABLE CATEGORY_FACET MODIFY APPLY_SUB_CATEGORIES VARCHAR2(1 BYTE);
ALTER TABLE CATEGORY_FACET MODIFY DEP_FACET_DISPLAY VARCHAR2(1 BYTE);
ALTER TABLE CATEGORY_FACET MODIFY DISPLAY VARCHAR2(1 BYTE);
ALTER TABLE CATEGORY_FACET MODIFY IS_ACTIVE VARCHAR2(2 BYTE);

ALTER TABLE FACET_ATTR_VALUE_ORDER MODIFY DO_NOT_DISPLAY VARCHAR2(1 BYTE);

ALTER TABLE BATCH_JOB_EXECUTION MODIFY JOB_INSTANCE_ID VARCHAR2(255 BYTE);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY STATUS VARCHAR2(255 BYTE);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY EXIT_MESSAGE VARCHAR2(255 BYTE);

ALTER TABLE PROMOS MODIFY PROMO_NAME VARCHAR2(150 CHAR);

ALTER TABLE KEYWORD_REDIRECTS MODIFY KEYWORD VARCHAR2(150 CHAR);
ALTER TABLE KEYWORD_REDIRECTS MODIFY REDIRECT_VALUE VARCHAR2(2048 CHAR);
ALTER TABLE KEYWORD_REDIRECTS MODIFY REDIRECT_TYPE VARCHAR2(10 CHAR);

ALTER TABLE BOOSTS_AND_BLOCKS MODIFY TERM VARCHAR2(200 BYTE);
ALTER TABLE BOOSTS_AND_BLOCKS MODIFY CATEGORY_ID VARCHAR2(25 BYTE);

ALTER TABLE BOOSTS_AND_BLOCKS_PRODUCTS MODIFY PRODUCT_NAME VARCHAR2(200 BYTE);

ALTER TABLE AF_BATCH_JOB_EXECUTION MODIFY JOB_INSTANCE_ID VARCHAR2(255 BYTE);
ALTER TABLE AF_BATCH_JOB_EXECUTION MODIFY STATUS VARCHAR2(255 BYTE);
ALTER TABLE AF_BATCH_JOB_EXECUTION MODIFY EXIT_MESSAGE VARCHAR2(255 BYTE);

ALTER TABLE FACETS_DISPLAY_ORDER MODIFY CATEGORY_NODE_ID VARCHAR2(50 CHAR);

ALTER TABLE SKU_HISTORY MODIFY SKU_ID VARCHAR2(50 BYTE);

CREATE INDEX IDX_SYNONYMS_01 ON SYNONYMS (UPPER(PRIMARY_TERM), UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_SYNONYMS_02 ON SYNONYMS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_SYNONYMS_03 ON SYNONYMS (STATUS_ID,UPDATED_DATE);
CREATE INDEX IDX_SYNONYMS_04 ON SYNONYMS (UPPER(DIRECTIONALITY), UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_SYNONYMS_05 ON SYNONYMS (UPPER(MATCH_TYPE), UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_SYNONYMS_06 ON SYNONYMS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
	
CREATE INDEX IDX_SYNONYM_TERMS_01 ON SYNONYM_TERMS (TERM);

CREATE INDEX IDX_KEYWORD_REDIRECTS_01 ON KEYWORD_REDIRECTS (UPPER(KEYWORD), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_02 ON KEYWORD_REDIRECTS (UPPER(REDIRECT_VALUE),UPDATED_DATE , STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_03 ON KEYWORD_REDIRECTS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_04 ON KEYWORD_REDIRECTS (STATUS_ID,UPDATED_DATE);
CREATE INDEX IDX_KEYWORD_REDIRECTS_05 ON KEYWORD_REDIRECTS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_06 ON KEYWORD_REDIRECTS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_KEYWORD_REDIRECTS_07 ON KEYWORD_REDIRECTS (END_DATE, UPDATED_DATE, STATUS_ID);

CREATE INDEX IDX_BANNERS_01 ON BANNERS (UPPER(BANNER_NAME), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_02 ON BANNERS (UPPER(BANNER_TYPE), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_03 ON BANNERS (UPPER(BANNER_PRIORITY), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_04 ON BANNERS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_05 ON BANNERS (END_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_06 ON BANNERS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BANNERS_07 ON BANNERS (UPDATED_DATE, STATUS_ID); 
CREATE INDEX IDX_BANNERS_08 ON BANNERS (STATUS_ID, UPDATED_DATE);

CREATE INDEX IDX_PROMOS_01 ON PROMOS (UPPER(PROMO_NAME), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_PROMOS_02 ON PROMOS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_PROMOS_03 ON PROMOS (STATUS_ID,UPDATED_DATE);
CREATE INDEX IDX_PROMOS_04 ON PROMOS (UPDATED_BY, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_PROMOS_05 ON PROMOS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_PROMOS_06 ON PROMOS (END_DATE, UPDATED_DATE, STATUS_ID);
	
CREATE INDEX IDX_PROMO_SKUS_01 ON PROMO_SKUS (SKU_ID);

CREATE INDEX IDX_FACETS_01 ON FACETS (UPPER(DISPLAY_NAME), UPPER(SYSTEM_NAME),UPDATED_BY, STATUS_ID);
CREATE INDEX IDX_FACETS_02 ON FACETS (STATUS_ID, UPDATED_DATE);
CREATE INDEX IDX_FACETS_03 ON FACETS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_FACETS_04 ON FACETS (START_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_FACETS_05 ON FACETS (END_DATE, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_FACETS_06 ON FACETS (UPDATED_BY, UPDATED_DATE, STATUS_ID);

CREATE INDEX IDX_BOOSTS_AND_BLOCKS_01 ON BOOSTS_AND_BLOCKS (UPPER(TERM), UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_02 ON BOOSTS_AND_BLOCKS (SEARCH_PROFILE_ID, STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_03 ON BOOSTS_AND_BLOCKS (CATEGORY_ID, UPDATED_DATE, STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_04 ON BOOSTS_AND_BLOCKS (UPDATED_DATE,STATUS_ID);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_05 ON BOOSTS_AND_BLOCKS (STATUS_ID, UPDATED_DATE);
CREATE INDEX IDX_BOOSTS_AND_BLOCKS_06 ON BOOSTS_AND_BLOCKS (UPDATED_BY, UPDATED_DATE, STATUS_ID);

commit;